#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
PURPLE='\033[1;35m'
NC='\033[0m' # No Color

export PS1="${PURPLE}\u${NC}@${RED}\h${NC}:${PURPLE}]\w${NC} # "

unset OS_AUTH_URL
unset OS_AUTH_VERSION
unset OS_IDENTITY_API_VERSION
unset OS_PROJECT_DOMAIN_NAME
unset OS_USER_DOMAIN_NAME
unset OS_DEFAULT_DOMAIN
unset OS_REGION_NAME
unset OS_PROJECT_NAME
unset OS_PROJECT_ID
unset OS_USERNAME
unset OS_PASSWORD
